<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function cdn_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
      case 'help.page.cdn':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The CDN module provides easy Content Delivery Network integration for Drupal sites. It alters file URLs, so that files (such as CSS, JS, images, fonts, videos …) are downloaded from a CDN instead of your web server. For more information, see the <a href=":online">online documentation for the CDN module</a>.', [':online' => 'https://www.drupal.org/docs/8/managing-site-performance-and-scalability/content-delivery-network-cdn']) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('General') . '</dt>';
      $output .= '<dd>' . t('A content delivery network (CDN) is a collection of web servers distributed across multiple locations to deliver content more efficiently to users. The server selected for delivering content to a specific user is typically based on a measure of network proximity.') . '</dd>';
      $output .= '<dt>' . t('Origin pull') . '</dt>';
      $output .= '<dd>' . t('The CDN module aims to support any CDN that supports <em>Origin Pull</em>. Pull requires virtually no work on your side: all you have to do, is rewrite the URLs to your files: replace your own domain name with the CDN’s domain name. The CDN will then apply the Origin Pull technique and will periodically pull the files from the origin (that is your server). How often that is, depends on how you have configured headers (particularly the Expires header).') . '</dd>';
      $output .= '</dl>';
      $output .= '<p>' . t('(ref: "Key Properties of a CDN." Weblog post. <em>Wim Leers.</em> Ed. Wim Leers. N.p., 26 Aug. 2009. Web. 18 Sept. 2016. <a href=":blog">http://www.wimleers.com/article/key-properties-of-a-cdn</a>.)', [':blog' => 'http://wimleers.com/article/key-properties-of-a-cdn']) . '</p>';
      return $output;
  }
}


/**
 * Implements hook_file_url_alter().
 */
function cdn_file_url_alter(&$uri) {
  // Don't alter file URLs when running update.php.
  if (defined('MAINTENANCE_MODE')) {
    return;
  }

  // Don't alter file URLs while processing a CSS file.
  // @see \Drupal\cdn\Asset\CssOptimizer
  global $cdn_in_css_file;
  if ($cdn_in_css_file) {
    return;
  }

  $result = \Drupal::service('cdn.file_url_generator')->generate($uri);
  if ($result) {
    $uri = $result;
  }
}
